### ISSUE TITLE
Change Learning Path to Module

### ISSUE THREAD

**Issue by AnnetteGill** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#141]
# Module: All
#### Step: 00

Description of issue

Please change the words "Learning path" in all lab exercises to "Module".  

The term "Learning Path" was discontinued in this course last year, and the term "Module" is used instead.  It confuses the students when they see Modules in their course manual and on my slides, but Learning Paths in the labs.

**Comment by tfrink** [comment]
Annette - During MS-100 and 101 pilot project last year, management made the decision to change from the ILT nomenclature of Module/Lesson/Topic to the Learn nomenclature of Learning Path/Module/Unit. Due to the negative feedback this decision invoked because of the SkillPipe UI change, we changed the terminology back in the SkillPipe UI, but I was specifically told to not change it back in the course content. Hence, the content refers to modules rather than lessons in the actual content. Same goes for the labs, which refer to Learning Paths rather than Modules. I will raise your concern with management, but until I am told to make this change, it will have to stay as is.

**Comment by AnnetteGill** [comment]
Thank you for raising this.  I don't see their rationale for leaving inconsistent terminology in the material.  It's just confusing, for no good reason that I can see.

One point:  the PPT slides WERE changed back to Modules.  The current situation is:

Skillpipe - Module/Lesson/Topic
PowerPoint slides - Module/Lesson/Topic
Labs - Learning Path

**Comment by tfrink** [comment]
Annette,

Well, sometimes miracles never cease. :) I got permission to change the labs to say Module. I'll pop those out ASAP.

Tony

**Comment by AnnetteGill** [comment]
Brilliant, thank you!
