### ISSUE TITLE
Module 3 - Lab 2 - Exercise 1 - Manage Administration Delegation

### ISSUE THREAD

**Issue by velden** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#6]
# Module: 3
#### Step: 30

Description of issue

Repro steps:

1. Unable for Lynne to block Nestor Wilke (who has Global Admin role) 
1.
1.

**Comment by tfrink** [comment]
It was determined that this lab broke due to a product change. When the lab was created, a non-Global admin could block a Global admin, so Lynne was able to block Nestor. However, the block sign-in functionality has now been updated to no longer allow this. The lab has been updated to instead have Lynne block Alex Wilber. It then has you try and block Nestor, only to be rejected. The lab explains why Lynne cannot block Nestor. The lab has also been updated to have the student try and log in as Alex, and then verify that the log in cannot be performed because his account has been blocked. Finally, to complete the cycle, the lab has Holly Spencer unblock Alex's account. This gives the student experience in both blocking and unblocking an account.
