### ISSUE TITLE
Api error creating resource (room) mailbox

### ISSUE THREAD

**Issue by FireyJoe** [MicrosoftLearning/MS-100T00-Microsoft-365-Identity-and-Services#63]
# Module: 4
## Lab/Demo: 3
##Exercise 1
#### Step: 10

Description of issue

Upon hitting "create" in step 10, an error is given on the Status page: "Resource mailbox creation failed! Not a Valid Object in Create Api Request.

Repro steps:

Perhaps a recent page change started producing this error. It seems to come up if you try to attach booking delegates on the previous pages of the wizard (i.e. Holly Dickson and Nestor Wilke). If you do not attach any delegates, you can create mailbox without an error. A potential workaround we found is to create the mailbox without delegates and then edit it to add them later.

![ms-100 exchange center resrouce mailbox creation error](https://user-images.githubusercontent.com/47234227/116757070-58579980-a9db-11eb-91dd-cbbf9924a002.JPG)

**Comment by geschwei** [comment]
Hello FieryJoe,

After testing out the lab several times. I'm not experiencing what you're describing. I believe this may be a one-off issue with the tenant specifically, or due to a problem during the time of the class which has now been resolved. please re-open the issue if it presents itself again.
